@startuml MER_Sistema_Manutencao

title "MER - Sistema de Gestão de Manutenção (MongoDB)"

entity "Responsavel" as Responsavel {
  * **_id : ObjectId**
  --
  * nome : String
  * cpf : String
  * email : String
  * cargo : String
  telefone : String
}

entity "Maquinario" as Maquinario {
  * **_id : ObjectId**
  --
  * tipo : String
  * marca : String
  * modelo : String
  * numeroSerie : String
  * anoFabricacao : Number
  * status : String
}

entity "Manutencao" as Manutencao {
  * **_id : ObjectId**
  --
  * titulo : String
  * observacao : String
  * dataAgendada : Date
  * status : String
  * custoEstimado : Number
  dataRealizada : Date
}

entity "Estoque" as Estoque {
    * **_id : ObjectId**
    --
    * nomeInventario : String
    * itens : Array
}

entity "Produto" as Produto {
  * **_id : ObjectId**
  --
  * nome : String
  * precoUnitario : Number
  categoria: String
  descricao : String
  codigoItem : String
}

' Relacionamentos
Maquinario "1" -- "0..*" Manutencao : possui
Responsavel "1" -- "0..*" Manutencao : é responsável por

Estoque "1" -- "0..*" Produto : cataloga

@enduml
