@startuml Diagrama de Casos de Uso

title Diagrama de Casos de Uso (Versão Simplificada)

left to right direction

actor "Colaborador" as user

rectangle "Sistema de Gestão de Manutenção" {
  usecase "Gerenciar Maquinários" as UC1
  usecase "Gerenciar Responsáveis" as UC2
  usecase "Gerenciar Estoque" as UC3
  usecase "Gerenciar Manutenções" as UC4
  usecase "Visualizar Dashboard" as UC5
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

@enduml
